name: CI Pipeline

on:
  push:
    branches: [ main ]  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub
      - name: Set up Java JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'  # Adjust if needed
          distribution: 'adopt'
      - name: Build project with Maven
        run: mvn -B package --file demo/pom.xml
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
           path:  ~/.m2/repository
           key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
           restore-keys: |
            ${{ runner.os }}-m2-
   
